export const eventLogs = {
  OVPUVP: {
    overVoltage1: "Over Voltage (stage 1)",
    overVoltage2: "Over Voltage (stage 2)",
    underVoltage1: "Under Voltage (stage 1)",
    underVoltage2: "Under Voltage (stage 2)",
    overTotalVoltage1: "Over Total Voltage (stage 1)",
    overTotalVoltage2: "Over Total Voltage (stage 2)",
    underTotalVoltage1: "Under Total Voltage (stage 1)",
    underTotalVoltage2: "Under Total Voltage (stage 2)",
  },
  OTPUTP: {
    overCHG_temper1: "Over CHG Temperature (stage 1)",
    overCHG_temper2: "Over CHG Temperature (stage 2)",
    underCHG_temper1: "Under CHG Temperature (stage 1)",
    underCHG_temper2: "Under CHG Temperature (stage 2)",
    overDSG_temper1: "Over DSG Temperature (stage 1)",
    overDSG_temper2: "Over DSG Temperature (stage 2)",
    underDSG_temper1: "Under DSG Temperature (stage 1)",
    underDSG_temper2: "Under DSG Temperature (stage 2)",
  },
  OCPSOC_protection: {
    overCHG_current1: "Over CHG Current (stage 1)",
    overCHG_current2: "Over CHG Current (stage 2)",
    overDSG_current1: "Over DSG Current (stage 1)",
    overDSG_current2: "Over DSG Current (stage 2)",
    overSOC1: "Over SOC (stage 1)",
    overSOC2: "Over SOC (stage 2)",
    underSOC1: "Under SOC (stage 1)",
    underSOC2: "Under SOC (stage 2)",
  },
  excessiveDifferentialValue: {
    overDifferentialVoltage1: "Over Differential Voltage (stage 1)",
    overDifferentialVoltage2: "Over Differential Voltage (stage 2)",
    overDifferentialTemper1: "Over Differential Temper (stage 1)",
    overDifferentialTemper2: "Over Differential Temper (stage 2)",
  },
  MOS_status: {
    CHGMOS_overTemper: "CHG MOS Over Temperature",
    DSGMOS_overTemper: "DSG MOS Over Temperature",
    CHGMOS_temperSensorDetectionFailure: "CHG MOS Temperature Sensor Detection Failure",
    DSGMOS_temperSensorDetectionFailure: "DSG MOS Temperature Sensor Detection Failure",
    CHGMOS_adhesionFailure: "CHG MOS Adhesion Failure",
    DSGMOS_adhesionFailure: "DSG MOS Adhesion Failure",
    CHGMOS_breakerFailure: "CHG MOS Breaker Failure",
    DSGMOS_breakerFailure: "DSG MOS Breaker Failure",
  },
  functionFault1: {
    AFE_chipMalfunction: "AFE Chip Malfunction",
    collectDropOff: "Collect Drop Off",
    temperatureSensorFault: "Temperature Sensor Fault",
    EEPROM_storageFailure: "EEPROM Storage Failure",
    RTC_clockMalfunction: "RTC Clock Malfunction",
    prechargeFailure: "Precharge Failure",
    communicationMalfunction1: "Communication Malfunction (stage 1)",
    communicationMalfunction2: "Communication Malfunction (stage 2)",
  },
  functionFault2: {
    currentModuleFailure: "Current Module Failure",
    mainVoltageDetectionSensor: "Main Voltage Detection Sensor",
    shortCircuitProtectionFailure: "Short Circuit Protection Failure",
    lowVoltageNoCharging: "Low Voltage No Charging",
    MOSGPS_orSoftSwitchMOSOFF: "MOSGPS or Soft Switch MOS OFF",
  },
};
